Bryan Martinez

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Populating Dataset
dataset = pd.read_csv(r'C:\Users\Bryan Martinez\react\prowrestleknow\DataCollector\RawResults.csv', encoding='ISO-8859-1')
dataset.head(5)

,company,show,year,month,day,competitors,winners,wins_by,stipulations,on_the_line,duration,main_event
0,WWE,Raw,2024,June,3,"Ludwig Kaiser, Sheamus",Ludwig Kaiser,pinfall,none,none,TBD,False
1,WWE,Raw,2024,June,3,"Finn Balor, Dragon Lee",Finn Balor,pinfall,none,none,TBD,False
2,WWE,Raw,2024,June,3,"Bron Breakker, Ricochet",Bron Breakker,pinfall,none,none,TBD,False
3,WWE,Raw,2024,June,3,"Kiana James, Natalya",Kiana James,pinfall,none,none,TBD,False
4,WWE,Raw,2024,June,3,"Braun Strowman, Carlito",Braun Strowman,pinfall,none,none,TBD,False

In [3]:
# Dataset Columns
dataset.columns

Index(['company', 'show', 'year', 'month', 'day', 'competitors', 'winners',
       'wins_by', 'stipulations', 'on_the_line', 'duration', 'main_event'],
      dtype='object')

In [4]:
# Checking for Null Data
dataset.isnull().sum()

company         0
show            0
year            0
month           0
day             0
competitors     0
winners         0
wins_by         0
stipulations    0
on_the_line     0
duration        0
main_event      0
dtype: int64

#   Adding Competitors to Dataset

In [5]:
all_names = set()
for competitors in dataset['competitors']:
    names = competitors.split(', ')
    all_names.update(names)

# Create a new DataFrame with the competitor names
filtered_dataset = pd.DataFrame({'wrestler_name': list(all_names)})
filtered_dataset.head()

    wrestler_name
0         Mia Yim
1      Dante Chen
2     Ari Daivari
3  Grayson Waller
4         The Miz

#   Adding to Amount of Matches Involved In

In [6]:
counts = []
for wrestler in filtered_dataset["wrestler_name"]:
    count = 0
    for matches in dataset['competitors']:
        names = matches.split(', ')
        if (wrestler in names):
            count+=1
    counts.append(count)
filtered_dataset['matches'] = counts

filtered_dataset.head(5)

    wrestler_name  matches
0         Mia Yim        2
1      Dante Chen        1
2     Ari Daivari        1
3  Grayson Waller        1
4         The Miz        1

#   Adding to Amount of Wins Involved In

In [7]:
counts = []
for wrestler in filtered_dataset["wrestler_name"]:
    count = 0
    for matches in dataset['winners']:
        names = matches.split(', ')
        if (wrestler in names):
            count+=1
    counts.append(count)
filtered_dataset['wins'] = counts

filtered_dataset.head(30)

                  wrestler_name  matches  wins
0                       Mia Yim        2     2
1                    Dante Chen        1     0
2                   Ari Daivari        1     1
3                Grayson Waller        1     1
4                       The Miz        1     1
5                     Johnny TV        1     0
6                  Shawn Spears        1     1
7                       Natalya        2     1
8                       Carlito        1     0
9                    Finn Balor        2     1
10                Stevie Turner        1     0
11                  Volador Jr.        1     0
12           Claudio Castagnoli        2     1
13                   Jay Lethal        1     0
14                 Jade Cargill        2     2
15                Shayna Bazler        2     0
16                       Saraya        1     1
17              Kris Statlander        1     1
18  Rugido (La Parka Negra III)        1     0
19                Lyra Valkyria        1     0
20                Kelani Jordan        2     1
21                    Thea Hail        1     0
22                     Sol Ruca        2     1
23                         Akam        2     1
24               Orange Cassidy        2     1
25                   Damon Kemp        1     0
26                Kofi Kingston        1     0
27               Campaign Singh        1     0
28                Candice LeRae        1     0
29                  Kiana James        1     1

#   Adding to Amount of Wins Via Variety of Ways
- pinfall, submission, dq, count out, etc.

# Adding Years Matches Competed from 1980 to 2024 (with # of Wins)

In [8]:
counts = []
for wrestler in filtered_dataset["wrestler_name"]:
    count = 0
    for matches in dataset['winners']:
        names = matches.split(', ')
        if (wrestler in names):
            count+=1
    counts.append(count)
filtered_dataset['wins'] = counts

filtered_dataset.head(30)

                  wrestler_name  matches  wins
0                       Mia Yim        2     2
1                    Dante Chen        1     0
2                   Ari Daivari        1     1
3                Grayson Waller        1     1
4                       The Miz        1     1
5                     Johnny TV        1     0
6                  Shawn Spears        1     1
7                       Natalya        2     1
8                       Carlito        1     0
9                    Finn Balor        2     1
10                Stevie Turner        1     0
11                  Volador Jr.        1     0
12           Claudio Castagnoli        2     1
13                   Jay Lethal        1     0
14                 Jade Cargill        2     2
15                Shayna Bazler        2     0
16                       Saraya        1     1
17              Kris Statlander        1     1
18  Rugido (La Parka Negra III)        1     0
19                Lyra Valkyria        1     0
20                Kelani Jordan        2     1
21                    Thea Hail        1     0
22                     Sol Ruca        2     1
23                         Akam        2     1
24               Orange Cassidy        2     1
25                   Damon Kemp        1     0
26                Kofi Kingston        1     0
27               Campaign Singh        1     0
28                Candice LeRae        1     0
29                  Kiana James        1     1

# Getting unique years

In [14]:
all_months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

all_years = set()
for year in dataset['year']:
    all_years.add(year)

['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
{2024}

# Final Results Gets Saved to New CSV File

In [ ]:

filtered_dataset.to_csv('./WrestlerInfo.csv', index=False, encoding='ISO-8859-1')